httpPort: "80"
httpsPort: "443"

routes:
  example.com:
    egressHostname: example.com
    port: "80"
    saml:
      example.com:
        url: https://example.com/saml
        issuer: https://example.com
        certPath: /path/to/cert
    oAuth:
      example.com:
        clientId: example.com
        clientSecret: example.com
