#!/bin/bash

openssl genrsa -out server.key 4096
openssl req -new -x509 -key server.key -out server.cert -days 365 -subj "/C=US/ST=South Dakota/L=Spearfish/O=Dev/OU=Dev/CN=Nick/emailAddress=nwneisen@gmail.com"
